### PR TITLE
Handle null version strings

### LINKED ISSUE #3: Null exception when querying for app version
### Summary
When using `getInstalledApps()` method to get the installed apps on my device, I'm getting a null exception inside the `models.dart` file where fromJson method looks for the `version` key in this line.
https://github.com/vishesh005/app_utils/blob/c6c24d4c60a23965b53fd1c3db49c4578529759c/lib/models.dart#L15

### Logs
```
I/flutter (17561): type 'Null' is not a subtype of type 'String'
I/flutter (17561): #0      BundleInfo.fromJson                                                            models.dart:15
I/flutter (17561): #1      AppUtils.getInstalledApps.<anonymous closure>                                        app_utils.dart:49
I/flutter (17561): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
I/flutter (17561): #3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
I/flutter (17561): #4      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162:27)
I/flutter (17561): #5      new _List.of (dart:core-patch/array.dart:127:20)
I/flutter (17561): #6      new List.of (dart:core-patch/array_patch.dart:49:20)
I/flutter (17561): #7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
I/flutter (17561): #8      AppUtils.getInstalledApps                                        app_utils.dart:50
I/flutter (17561): <asynchronous suspension>
I/flutter (17561): #9      getInstalledApps                                        apps_service.dart:65
I/flutter (17561): <asynchronous suspension>
```

### Code
This is the code I wrote using the package
```dart
  List<BundleInfo> apps = await AppUtils.getInstalledApps();
  List<Map<String, String>> finalList = [];
  for (var element in apps) {
    finalList.add({
      'name': element.appName,
      'package': element.appIdentifier,
      'version': element.version,
    });
  }
```

### PR DESCRIPTION
**Pull request by ashwinkey04**
Fixes #3

### CODE REVIEW

**Comment by vishesh005** [comment]
Thank you @ashwinkey04  for your contribution. I am excited about the prospect of your future contributions."

**Comment by vishesh005** [comment]
I'll also be pushing it to pub.dev tomorrow.

**Comment by ashwinkey04** [comment]
You're welcome @vishesh005. But I suppose you meant to merge this PR, this was closed instead.

**Comment by vishesh005** [comment]
@ashwinkey04  Done.

**Pull request merged**
